export { default as Home } from './Home'
export { default as LandingPage } from './LandingPage'
export { default as ArtistList } from './ArtistList'
export { default as Children } from './Children'
export { default as PLaylistList  } from "./PlaylistList"
export { default as Artists } from './Artists'
export { default as Songs } from './Songs'
export { default as DetailArtist } from './DetailArtist'
export { default as ProfilePage } from './ProfilePage'